language: android

jdk: oraclejdk8

script: ./gradlew clean build

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "p+xh1zsxD3gRo4xtzphefLRThsI2QKTqSiCKA+gZojMILDliXf9SZsgeyICihhRSyJ+5DJXgRrqykCaY59aokbuDCRfiRhzDL6LLSe4dFJIEDa7r6Cq3otD+my4IrxmoTvunDb85uqrUl13B6OLYlXvhPVFloh+IbS9hkco4PNrldwEpZXGDx0Wh0txVCt6Sluv80/nIjbiPw49wv/JtZU+Scvn099dvN0Bl0BrXBxiLbjz0jE1N395ysEvTNwIujw6jnLFcWe7ZtFqUmoJOk+L49273iLLdWaK3U5WQ9PK/P4l0uc9fARjIRhnOo36Jfet9orGEC4YSueumbp9b7iqw2x7/6GBuwvxVWiE7GFUVNgvFdqGKe/KwNsjEmL/PlUJ04mobtNNlHXM29GPPxoMBzsv4Z9BI/gjwIv2BmTPhH2kjpBk+wE7U0NHMjSISMh7rBrw8dOdpxipvGIpfh0tVwSMG32Rxfbo7QdtknKfI99NYgdtrZuNfTaKMnGZVjhzyB8WjKS1xf4kvg8/UDd6Pj/e3FMVAAf9+yLzuz78FCv26v/+X2cidIt4V5JCXXB/QOg84SALgajGcdzhwN91mhuOU9XUAG6Mbo6G3eNqXt1XNqM0G+upFvKaC+YXCFrDteXajPihB+mPB7HbHTazodwf1PziHs0/Ps0Bafxo="
    - secure: "Y0UWmoZlVBne07XStMSUMOgW0YnBIwJqFExHTedvZ859PXh+Yryf8dErztPmWn4rqGSnJ5ZVeLyVHnCNJSKvWNXU9vb+JVFpp53/cfbkplrrbQYfihThgKtHAFpg7RUhGuyrAs1i9gKBSoaDwFK6NH68C225CcvgR2DtwO1C2n6QR0XW8jT7FcMXdo44Exy7DjQUDhuRITvdMouFXDlpECqblVMP8+9YAE/Bul9KuXcB4EpR5LqEmqKu/YFz+nMC6kQVMFtjlMSVCpC6d2vLg53FR5jnW9tyBG4rxjTaEaNj8jQonwgBoTUI7GwcmSwk5/PwIgazwLd8xncmg2dLi9zONXvma17fl8edavRFO7ji5lv7aCRlvKFkniB55V65zPX9xeIIAGuHTdH8lqRLXpmTe9cIxPzztf7aj+FG0S+/44c3nHaIOSUmPDqgnrTe34MSiwc9mqmHRjkt+zUGKT2j2ZzydFLi1GKZdOc2I8JjVh/sE+oFKy8uFqGgBm0pcPJJlnCruOt7OdTly/E+Xvr3g1Aq2qx7Vy3MT7cOtKDgOZfGWOuyGMeMZK+F690OjEaxd4rxmJN1+P34SGTHi7ZvfnpCNElOOXIre0A7KTjgZfZ6dds6hSSx3d/opV0vicudBUG9fV3i0FW7h+6/M32v7ZxKsB17o8cByNbxFH0="

branches:
  except:
    - gh-pages

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
